### ISSUE TITLE
Remove the burn and _deleteTimelock functions

### ISSUE THREAD

**Issue by aquabu** [CoMakery/TokenLockup#32]
# Motivation
The functions for `burn` and `deleteTimeLock` provide a way to punish trolls that create spam timelocks and make the `transfer()` function that loops over an array of all of the user's timelocks either expensive or unusable. The minimum funding amount makes spam timelocks expensive. The `burn()` function was intended to make spam timelocks both expensive and easy to remove.

However there are two side effects to this approach we should fix:

* Efficiently deleting the timelock reorders timelock indexes. This is bad for dApps that refer to and cache the timelock index. This could cause issues. Solutions like keeping the id separate from the timelock will increase the amount of storage required and the total gas fees. Increasing gas costs is highly undesirable at current Ethereum gas prices.
* Requiring that token has a burn function limits the usefulness of the TokenLockup contract. Generic ERC20s that do not have a burn function wouldn't be able to use the contract.

Furthermore, it's possible to directly transfer from a specific timelock using `transferTimelock()`. The `transfer()` function that draws its balance from all of a users timelocks is a convenience function.

Given these things it makes sense to remove both the burn and delete timelocks.

# To be done

* Remove `burn` function: https://github.com/CoMakery/TokenLockup/blob/60859cf5aa6f6db91b076646c56a9f4e86f1e1e2/contracts/TokenLockup.sol#L433
* Remove `_deleteTimelock()` https://github.com/CoMakery/TokenLockup/blob/60859cf5aa6f6db91b076646c56a9f4e86f1e1e2/contracts/TokenLockup.sol#L448
* Replace the `IERC20Burnable` import  with a `IERC20` interface https://github.com/CoMakery/TokenLockup/blob/60859cf5aa6f6db91b076646c56a9f4e86f1e1e2/contracts/TokenLockup.sol#L2
*  Remove the `IERC20Burnable` interface file - check if the `function decimals() external view returns (uint8);` portion of the interface needs to be included https://github.com/CoMakery/TokenLockup/blob/60859cf5aa6f6db91b076646c56a9f4e86f1e1e2/contracts/IERC20Burnable.sol

**Comment by voyager-gold** [comment]
@aquabu `cancelTimelock` has a dependency on `_deleteTimeLock` and if we remove `_deleteTimeLock` how do we handle with `cancelTimeLock`?
